version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - npm ci
  build:
    commands:
      - echo Building the React App...
      - npm run build
      - echo "Listing contents of dist directory:"
      - ls -la dist/
      - echo "Listing contents of dist/assets directory:"
      - ls -la dist/assets/
  post_build:
    commands:
      - echo "Creating zip file..."
      - cd dist
      - zip -r ../dist.zip .
      - cd ..
      - echo "Verifying zip contents:"
      - unzip -l dist.zip
artifacts:
  files:
    - dist.zip
  base-directory: .
  name: react-app-build-project
  discard-paths: no 