version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - npm ci
  build:
    commands:
      - echo Building the React App...
      - npm run build
  post_build:
    commands:
      - echo Zipping the build output...
      - zip -r dist.zip dist/*
artifacts:
  files:
    - dist.zip
  base-directory: .
  name: react-app-build-project 